sudo: required
dist: trusty

language: cpp
compiler:
  - gcc

os:
  - linux
  - osx
  - windows
  
    
script:
  - cd TBParser
  - chmod +x install-sh
  - ./install_deps.sh
  - ./configure && make && make install
